version: '3'
services:
  zk:
    image: zookeeper:3.6
    container_name: spike-dev-zk
    hostname: zoo1
    restart: "no"
    ports:
      - 2181:2181
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    networks:
      spike_default_network:
  db:
    image: mysql:5.7
    container_name: spike-dev-db
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: "no"
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spike_core_product
    networks:
      spike_default_network:
  redis:
    image: redis
    container_name: spike-dev-redis
    hostname: redis1
    restart: "no"
    ports:
      - 16379:6379
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    networks:
      spike_default_network:
# apache/dubbo-admin
  da:
    image: apache/dubbo-admin
    depends_on:
      - zk
    container_name: spike-dev-dubbo-admin
    hostname: zoo1
    restart: "no"
    ports:
      - 18080:8080
    environment:
      - admin.registry.address=zookeeper://zk:2181
      - admin.config-center=zookeeper://zk:2181
      - admin.metadata-report.address=zookeeper://zk:2181
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    networks:
      spike_default_network:
  # mq:
  #   image: rabbitmq:3-management
  #   container_name: spike-dev-mq
  #   restart: "no"
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #     - 25672:25672
  #     - 15671:15671
  #     - 5671:5671
  #     - 4369:4369
  #   networks:
  #     spike_default_network:
networks:
  spike_default_network:
